	<program>
		<date><?= $this->escape($this->date) ?></date>
		<start_time><?= $this->escape($this->start_time) ?></start_time>
		<leadtext><?= $this->escape($this->leadtext) ?></leadtext>
		<name><?= $this->escape($this->name) ?></name>
		<b-line><?= $this->escape($this->b_line) ?></b-line>
		<synopsis><?= $this->escape($this->synopsis) ?></synopsis>
		<url><?= $this->escape($this->url) ?></url>
	</program>
