<?= $this->doctype() ?>

<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
	<head>
<?= $this->headMeta()->setIndent("\t\t") ?>
	
<?= $this->headTitle('Worksample')->setIndent("\t\t") ?>
	
<?= $this->headLink()->setIndent("\t\t") ?>

<?= $this->headScript()->setIndent("\t\t") ?>

	</head>
	<body>
		<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
		<header class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="#">Worksample</a>
					<div class="nav-collapse">
						<ul class="nav">
							<li><a href="#modal-program" data-toggle="modal"><i class="icon-file icon-white"></i> <?= $this->translate('Add program') ?></a></li>
							<li><a href="#reload" class="program-list-reload"><i class="icon-repeat icon-white"></i> <?= $this->translate('Reload') ?></a></li>
							<li><a href="#modal-information" data-toggle="modal"><i class="icon-info-sign icon-white"></i> <?= $this->translate('Information') ?></a></li>
							<li class="dropdown">
								<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="icon-download icon-white"></i> <?= $this->translate('Export') ?>  <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="<?= $this->url(array('controller' => 'program', 'action' => 'export', 'format' => 'xml')) ?>">Xml</a></li>
									<li><a href="<?= $this->url(array('controller' => 'program', 'action' => 'export', 'format' => 'json')) ?>">Json</a></li>
									<li><a href="<?= $this->url(array('controller' => 'program', 'action' => 'export', 'format' => 'csv')) ?>">Csv</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</header>
		<div class="container-fluid">
			<?= $this->layout()->content ?>
		</div>
		<footer>
		
		</footer>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>
<?= $this->footScript()->setIndent("\t\t")->appendFile('/js/bootstrap.js')->appendFile('/js/script.js') ?>

	</body>
</html>
</html>